name: screenm
channels:
    - conda-forge
    - bioconda
    - defaults

dependencies:
  - python>3.13
  - snakemake>=8.0.1
  - biopython>=1.85
  - numpy==2.3.3
  - pandas==2.3.3
  - PyYAML==6.0.3
  - requests==2.32.5
  - pip==25.2
  - pip:
      - git+https://github.com/alberdilab/screenm.git
      - argparse